/*
const addnumbers = () : void  => console.log(2+3);
addnumbers();

const throwNewError = () : never => { 
   throw new Error('Your Program Terminated because of error')
};
throwNewError()
*/